name       : python-poetry
version    : 1.5.1
release    : 5
source     :
    # The bootstrap source needs to be from pypi as it's the only source with a setup.py
    - https://pypi.io/packages/source/p/poetry/poetry-1.5.1.tar.gz : cc7ea4524d1a11558006224bfe8ba8ed071417d4eb5ef6c89decc6a37d437eeb
license    : MIT
component  : programming.python
summary    : Python dependency management and packaging made easy.
description: |
    Poetry helps you declare, manage and install dependencies of Python projects, ensuring you have the right stack everywhere.
builddeps  :
    - pkgconfig(python3)
    - python-build
    - python-installer
    - python-packaging
    - python-poetry
    - python-wheel
rundeps    :
    - python-cachecontrol
    - python-cachy
    - python-cffi
    - python-cleo
    - python-crashtest
    - python-cryptography
    - python-dulwich
    - python-html5lib
    - python-lockfile
    - python-msgpack
    - python-pkginfo
    - python-poetry-core
    - python-requests-toolbelt
    - python-shellingham
    - python-tomlkit
    - virtualenv
build      : |
    %python3_setup
install    : |
    %python3_install
