name       : python-poetry
version    : 1.1.11
release    : 1
source     :
    # The bootstrap source needs to be from pypi as it's the only source with a setup.py
    - https://pypi.io/packages/source/p/poetry/poetry-1.1.11.tar.gz : 7d7d22f55fbebb830cc85b1c69cd7a91fd85f49e5396e7a14b953645a470f69e
license    : MIT
component  : programming.python
summary    : Python dependency management and packaging made easy.
description: |
    Poetry helps you declare, manage and install dependencies of Python projects, ensuring you have the right stack everywhere.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-cachecontrol
    - python-cachy
    - python-cffi
    - python-cleo
    - python-clikit
    - python-crashtest
    - python-cryptography
    - python-html5lib
    - python-msgpack
    - python-pkginfo
    - python-poetry-core
    - python-requests-toolbelt
    - python-shellingham
    - python-tomlkit
    - virtualenv
setup      : |
    %patch -p1 < $pkgfiles/0001-newer-keyring.patch
build      : |
    %python3_setup
install    : |
    %python3_install
